### ISSUE TITLE
priority_order missing default value when adding an issue

### ISSUE THREAD

**Issue by chrisforrence** [modestkdr/Scrumwala#3]
When I attempt to insert an issue into the database, I get the following exception:

```
SQLSTATE[HY000]: General error: 1364 Field 'priority_order' doesn't have a default value (SQL: insert into `issues` (`title`, `description`, `project_id`, `deadline`, `type_id`, `user_id`, `sprint_id`, `status_id`, `updated_at`, `created_at`) values (test, test, 2, 2015-04-05 23:55:55, 3, 1, 2, 2, 2015-06-11 17:10:26, 2015-06-11 17:10:26))
```

**Comment by modestkdr** [comment]
@chrisforrence I wasn't able to replicate this issue on my local and prod. environments. Do you still have this issue?

**Comment by chrisforrence** [comment]
I just re-cloned, re-migrated, and I'm getting the same behavior.

MySQL Server: 5.6.25
PHP: 5.5.20

I'm able to reproduce it as easily as re-cloning/re-migrating, then creating a new project (which successfully saves), then attempting to create a new issue.

When I took a look at your migration file for issues (2015_03_23_002918_create_issues_table.php), I saw a priority_order column (`$table->integer('priority_order')->unsigned();`). Do you have everything checked in and pushed to master?

Cheers!

**Comment by modestkdr** [comment]
@chrisforrence  I added a default of zero to the priority_order column. 
$table->integer('priority_order')->unsigned()->default(0); 
This is a temporary fix. I plan on using a separate table to store the sort order for issues.

**Comment by chrisforrence** [comment]
Ah, ok. Assuming that priority_order will be something like 1=Trivial, 2=Minor, 3=Major, 4=Critical?

**Comment by modestkdr** [comment]
@chrisforrence  let me back up a step. 'priority_order' column was meant to store the sort order for issues. In the project: plan view, when an issue is dragged and dropped into a another sprint/backlog, apart from change in the 'sprint' association, the sort order of the issue changes (like 2nd in Sprint B to lets say 5th in Sprint D). I realized that the sort order has to be stored as a linked list in a table since the order is relative to other issues.

Anyway, I might as as well remove the priority_order column for now. 
To your point about priority order (Trivial, Minor etc.,) I am not a big fan of this feature and, it creates an extra form field when creating an issue.
if this feature existed would you use it?

**Comment by chrisforrence** [comment]
Ah, gotcha. I understand now what you're getting at with priority_order; I was misinterpreting what you were getting at.And yeah, you'd probably need to do some sort of linked-list (perhaps replacing priority_order with sort_node_prev and sort_node_next?)

I would likely use priority order to some degree; for issues that pop up, I would want to be able to easily differentiate between low-priority items and higher-priority items. I wouldn't say it's a necessity, however.

**Comment by chrisforrence** [comment]
I'll go ahead and close this out, since the underlying issue (priority_order's missing default value) has been fixed.

**Comment by modestkdr** [comment]
Cool.
